version: "3.8"

services:
  postgresql:
    image: postgres:16-alpine
    ports:
      - "1818:5432"
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile
    container_name: ai-lovly-guu
    env_file:
      - .env
    depends_on:
      - postgresql
    networks:
      - internal
networks:
  internal:
    name: ${APP_NAME}-net
