name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build m1 Docker image
        run: docker build . --file docker/dev/m1/Dockerfile --tag ${{ secrets.REGISTRY_URL }}/app-m1:latest

      - name: Build m2 Docker image
        run: docker build . --file docker/dev/m2/Dockerfile --tag ${{ secrets.REGISTRY_URL }}/app-m2:latest

  push-registry:
    needs: build  # Зависит от успешного выполнения задачи build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker registry
        run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push to registry m1 Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/app-m1:latest

      - name: Push to registry m2 Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/app-m2:latest
